spring:
  datasource:
    url: jdbc:mysql://www.zealot.group:3306/king?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zealot
    password: zealot
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: false
      idle-timeout: 30000
      pool-name: hikariPool
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

    redis:
      host: www.zealot.group
      port: 6379
      password: zealot
      database: 0
      timeout: 60s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
      # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
      lettuce:
        pool:
          # 最大空闲连接数
          max-idle: 500
          # 最小空闲连接数
          min-idle: 50
          # 等待可用连接的最大时间，负数为不限制
          max-wait:  -1s
          # 最大活跃连接数，负数为不限制
          max-active: -1
    activemq:
      user: zealot
      password: zealot
      broker-url: tcp://www.zealot.group:61616
      in-memory: false
      #必须使用连接池
      pool:
        #启用连接池
        enabled: true
        #连接池最大连接数
        max-connections: 5
        #空闲的连接过期时间，默认为30秒
        idle-timeout: 30s
      redeliveryPolicy:
        useExponentialBackOff: false
        backOffMultiplier: 1.0
        maximumRedeliveries: 10
        maximumRedeliveryDelay: 10000
        initialRedeliveryDelay: 2000
      task:
        execution:
          threadNamePrefix: task-execution
          pool:
            coreSize: 30
        scheduling:
          threadNamePrefix: task-scheduling
          pool:
            size: 10
    mvc:
      throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false

    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
  server:
    port: 8080
    servlet:
      context-path: /api
    tomcat:
      uri-encoding: UTF-8
  mybatis:
    typeAliasesPackage: group.zealot.king
    mapperLocations: classpath*:mapper/**/*.xml
  dubbo:
    application:
      name: demo.api
    protocol:
      name: dubbo
      port: -1
    registry:
      address: zookeeper://127.0.0.1:2181
      protocol: dubbo
      check: false
    provider:
      timeout: 2000
      retries: 0
      loadbalance: leastactive
    consumer:
      check: false
      async: false